# Generated by Django 5.0.6 on 2024-05-19 20:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baby",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("parent_name", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "babies",
            },
        ),
        migrations.CreateModel(
            name="BabySitter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=6
                    ),
                ),
                ("next_of_kin_name", models.CharField(max_length=100)),
                (
                    "nin",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(14)],
                    ),
                ),
                ("recommender_name", models.CharField(max_length=100)),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "level_of_education",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Primary", "Primary"),
                            ("High School", "High School"),
                            ("Bachelor's", "Bachelor's"),
                            ("Masters", "Masters"),
                        ],
                        max_length=50,
                    ),
                ),
                ("contact", models.CharField(max_length=10, unique=True)),
                ("is_off_duty", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "baby_sitters",
            },
        ),
        migrations.CreateModel(
            name="BabySitting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drop_off_person_name", models.CharField(max_length=100)),
                ("arrival_time", models.DateTimeField()),
                (
                    "period_of_stay",
                    models.CharField(
                        choices=[("Half Day", "Half Day"), ("Full Day", "Full Day")],
                        max_length=8,
                    ),
                ),
                (
                    "pick_up_person_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("fee", models.IntegerField(blank=True, default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="baby_sittings",
                        to="baby_sitting.baby",
                    ),
                ),
                (
                    "baby_sitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="baby_sittings",
                        to="baby_sitting.babysitter",
                    ),
                ),
            ],
            options={
                "db_table": "baby_sittings",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baby",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="payments",
                        to="baby_sitting.baby",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
    ]
